In [31]:
import numpy as np
import pandas as pd
autos = pd.read_csv('../data/Auto.csv')
print(type(autos))
print(f'dimensions: {autos.shape}')
autos

<class 'pandas.core.frame.DataFrame'>
dimensions: (392, 9)

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
387,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
388,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
389,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
390,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
391,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

SELECTING ROWS AND COLUMNS OF A DATAFRAME

Indexes for columns:

In [32]:
autos.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin', 'name'],
      dtype='object')

Indexes for rows: automatic and ad-hoc.

In [33]:
autos.index

RangeIndex(start=0, stop=392, step=1)

In [34]:
autos_index_col = autos.set_index('name')
autos_index_col

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin
name,,,,,,,,
chevrolet chevelle malibu,18.0,8,307.0,130,3504,12.0,70,1
buick skylark 320,15.0,8,350.0,165,3693,11.5,70,1
plymouth satellite,18.0,8,318.0,150,3436,11.0,70,1
amc rebel sst,16.0,8,304.0,150,3433,12.0,70,1
ford torino,17.0,8,302.0,140,3449,10.5,70,1
...,...,...,...,...,...,...,...,...
ford mustang gl,27.0,4,140.0,86,2790,15.6,82,1
vw pickup,44.0,4,97.0,52,2130,24.6,82,2
dodge rampage,32.0,4,135.0,84,2295,11.6,82,1
ford ranger,28.0,4,120.0,79,2625,18.6,82,1
chevy s-10,31.0,4,119.0,82,2720,19.4,82,1

The variable 'name' is not already present in the indexes for columns:

In [35]:
autos_index_col.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin'],
      dtype='object')

Selecting rows: the three first rows.

In [36]:
autos[:3]

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite

Selecting by the index of rows (names):

In [47]:
print(autos_index_col.index)
rows_ex = ['ford torino', 'chevrolet impala']
autos_index_col.loc[rows_ex]

Index(['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite',
       'amc rebel sst', 'ford torino', 'ford galaxie 500', 'chevrolet impala',
       'plymouth fury iii', 'pontiac catalina', 'amc ambassador dpl',
       ...
       'chrysler lebaron medallion', 'ford granada l', 'toyota celica gt',
       'dodge charger 2.2', 'chevrolet camaro', 'ford mustang gl', 'vw pickup',
       'dodge rampage', 'ford ranger', 'chevy s-10'],
      dtype='object', name='name', length=392)

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin
name,,,,,,,,
ford torino,17.0,8,302.0,140,3449,10.5,70,1
chevrolet impala,14.0,8,454.0,220,4354,9.0,70,1
chevrolet impala,14.0,8,350.0,165,4209,12.0,71,1
chevrolet impala,13.0,8,350.0,165,4274,12.0,72,1
chevrolet impala,11.0,8,400.0,150,4997,14.0,73,1

Selecting rows by a list of numbers:

In [49]:
autos_index_col.iloc[[3,4]]

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin
name,,,,,,,,
amc rebel sst,16.0,8,304.0,150,3433,12.0,70,1
ford torino,17.0,8,302.0,140,3449,10.5,70,1

In [50]:
autos.iloc[[3,4]]

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

A boolean filter

In [52]:
filter_horsepow = autos['horsepower'] > 215
autos[filter_horsepow]

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name
6,14.0,8,454.0,220,4354,9.0,70,1,chevrolet impala
8,14.0,8,455.0,225,4425,10.0,70,1,pontiac catalina
13,14.0,8,455.0,225,3086,10.0,70,1,buick estate wagon (sw)
94,12.0,8,455.0,225,4951,11.0,73,1,buick electra 225 custom
115,16.0,8,400.0,230,4278,9.5,73,1,pontiac grand prix

Selecting columns:

In [51]:
horsepow_var = autos['horsepower']
print(type(horsepow_var))
print(horsepow_var)
print('sum' , sum(horsepow_var))

<class 'pandas.core.series.Series'>
0      130
1      165
2      150
3      150
4      140
      ...
387     86
388     52
389     84
390     79
391     82
Name: horsepower, Length: 392, dtype: int64
sum 40952

In [53]:
np.unique(horsepow_var)

array([ 46,  48,  49,  52,  53,  54,  58,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98, 100, 102, 103, 105, 107, 108, 110,
       112, 113, 115, 116, 120, 122, 125, 129, 130, 132, 133, 135, 137,
       138, 139, 140, 142, 145, 148, 149, 150, 152, 153, 155, 158, 160,
       165, 167, 170, 175, 180, 190, 193, 198, 200, 208, 210, 215, 220,
       225, 230])

In [54]:
autos[['mpg', 'horsepower']]

      mpg  horsepower
0    18.0         130
1    15.0         165
2    18.0         150
3    16.0         150
4    17.0         140
..    ...         ...
387  27.0          86
388  44.0          52
389  32.0          84
390  28.0          79
391  31.0          82

[392 rows x 2 columns]

Selecting columns by a list of numbers:

In [55]:
autos_index_col.iloc[:, [1,2]]

                           cylinders  displacement
name
chevrolet chevelle malibu          8         307.0
buick skylark 320                  8         350.0
plymouth satellite                 8         318.0
amc rebel sst                      8         304.0
ford torino                        8         302.0
...                              ...           ...
ford mustang gl                    4         140.0
vw pickup                          4          97.0
dodge rampage                      4         135.0
ford ranger                        4         120.0
chevy s-10                         4         119.0

[392 rows x 2 columns]

Selecting a combination of rows and columns:

In [57]:
autos.iloc[[2,3],[1,2]]

   cylinders  displacement
2          8         318.0
3          8         304.0

A combination of index row and column names:

In [59]:
autos_index_col.loc[['chevrolet impala', 'ford torino'], ['cylinders', 'displacement']]

                  cylinders  displacement
name
chevrolet impala          8         454.0
chevrolet impala          8         350.0
chevrolet impala          8         350.0
chevrolet impala          8         400.0
ford torino               8         302.0

Selecting rows with lambda and a list of columns.

In [60]:
autos_index_col.loc[lambda df: df['cylinders'] == 8, ['weight','displacement']]

                                      weight  displacement
name
chevrolet chevelle malibu               3504         307.0
buick skylark 320                       3693         350.0
plymouth satellite                      3436         318.0
amc rebel sst                           3433         304.0
ford torino                             3449         302.0
...                                      ...           ...
chevrolet malibu classic (sw)           3605         267.0
chrysler lebaron town @ country (sw)    3940         360.0
cadillac eldorado                       3900         350.0
oldsmobile cutlass salon brougham       3420         260.0
oldsmobile cutlass ls                   3725         350.0

[103 rows x 2 columns]

In [63]:
autos_index_col.loc[lambda df: (df['cylinders'] == 8) & (df.index.str.contains('ford') |
                               df.index.str.contains('datsun')), ['weight', 'displacement', 'cylinders']]

                          weight  displacement  cylinders
name
ford torino                 3449         302.0          8
ford galaxie 500            4341         429.0          8
ford f250                   4615         360.0          8
ford galaxie 500            4154         351.0          8
ford country squire (sw)    4746         400.0          8
ford galaxie 500            4129         351.0          8
ford gran torino (sw)       4294         302.0          8
ford gran torino            4042         302.0          8
ford ltd                    4363         351.0          8
ford country                4906         400.0          8
ford gran torino            4141         302.0          8
ford gran torino (sw)       4638         302.0          8
ford ltd                    4657         351.0          8
ford mustang ii             3169         302.0          8
ford gran torino            4215         351.0          8
ford f108                   3870         302.0          8
ford thunderbird            4335         351.0          8
ford futura                 3205         302.0          8
ford ltd landau             3725         302.0          8
ford country squire (sw)    4054         351.0          8