In [1]:
from sklearn.neighbors import KNeighborsClassifier as KNN
import common_mod_1 as cmm

In [2]:
adult_census = cmm.dfFromArffFile('/data/phpMawTba.arff')
adult_census.head(10)

Metadata =============================================
 Dataset: adult
	age's type is numeric
	workclass's type is nominal, range is ('Private', 'Self-emp-not-inc', 'Self-emp-inc', 'Federal-gov', 'Local-gov', 'State-gov', 'Without-pay', 'Never-worked')
	fnlwgt's type is numeric
	education's type is nominal, range is ('Bachelors', 'Some-college', '11th', 'HS-grad', 'Prof-school', 'Assoc-acdm', 'Assoc-voc', '9th', '7th-8th', '12th', 'Masters', '1st-4th', '10th', 'Doctorate', '5th-6th', 'Preschool')
	education-num's type is numeric
	marital-status's type is nominal, range is ('Married-civ-spouse', 'Divorced', 'Never-married', 'Separated', 'Widowed', 'Married-spouse-absent', 'Married-AF-spouse')
	occupation's type is nominal, range is ('Tech-support', 'Craft-repair', 'Other-service', 'Sales', 'Exec-managerial', 'Prof-specialty', 'Handlers-cleaners', 'Machine-op-inspct', 'Adm-clerical', 'Farming-fishing', 'Transport-moving', 'Priv-house-serv', 'Protective-serv', 'Armed-Forces')
	relationship's type is nominal, range is ('Wife', 'Own-child', 'Husband', 'Not-in-family', 'Other-relative', 'Unmarried')
	race's type is nominal, range is ('White', 'Asian-Pac-Islander', 'Amer-Indian-Eskimo', 'Other', 'Black')
	sex's type is nominal, range is ('Female', 'Male')
	capital-gain's type is numeric
	capital-loss's type is numeric
	hours-per-week's type is numeric
	native-country's type is nominal, range is ('United-States', 'Cambodia', 'England', 'Puerto-Rico', 'Canada', 'Germany', 'Outlying-US(Guam-USVI-etc)', 'India', 'Japan', 'Greece', 'South', 'China', 'Cuba', 'Iran', 'Honduras', 'Philippines', 'Italy', 'Poland', 'Jamaica', 'Vietnam', 'Mexico', 'Portugal', 'Ireland', 'France', 'Dominican-Republic', 'Laos', 'Ecuador', 'Taiwan', 'Haiti', 'Columbia', 'Hungary', 'Guatemala', 'Nicaragua', 'Scotland', 'Thailand', 'Yugoslavia', 'El-Salvador', 'Trinadad&Tobago', 'Peru', 'Hong', 'Holand-Netherlands')
	class's type is nominal, range is ('>50K', '<=50K')

None

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
0,25.0,b'Private',226802.0,b'11th',7.0,b'Never-married',b'Machine-op-inspct',b'Own-child',b'Black',b'Male',0.0,0.0,40.0,b'United-States',b'<=50K'
1,38.0,b'Private',89814.0,b'HS-grad',9.0,b'Married-civ-spouse',b'Farming-fishing',b'Husband',b'White',b'Male',0.0,0.0,50.0,b'United-States',b'<=50K'
2,28.0,b'Local-gov',336951.0,b'Assoc-acdm',12.0,b'Married-civ-spouse',b'Protective-serv',b'Husband',b'White',b'Male',0.0,0.0,40.0,b'United-States',b'>50K'
3,44.0,b'Private',160323.0,b'Some-college',10.0,b'Married-civ-spouse',b'Machine-op-inspct',b'Husband',b'Black',b'Male',7688.0,0.0,40.0,b'United-States',b'>50K'
4,18.0,b'?',103497.0,b'Some-college',10.0,b'Never-married',b'?',b'Own-child',b'White',b'Female',0.0,0.0,30.0,b'United-States',b'<=50K'
5,34.0,b'Private',198693.0,b'10th',6.0,b'Never-married',b'Other-service',b'Not-in-family',b'White',b'Male',0.0,0.0,30.0,b'United-States',b'<=50K'
6,29.0,b'?',227026.0,b'HS-grad',9.0,b'Never-married',b'?',b'Unmarried',b'Black',b'Male',0.0,0.0,40.0,b'United-States',b'<=50K'
7,63.0,b'Self-emp-not-inc',104626.0,b'Prof-school',15.0,b'Married-civ-spouse',b'Prof-specialty',b'Husband',b'White',b'Male',3103.0,0.0,32.0,b'United-States',b'>50K'
8,24.0,b'Private',369667.0,b'Some-college',10.0,b'Never-married',b'Other-service',b'Unmarried',b'White',b'Female',0.0,0.0,40.0,b'United-States',b'<=50K'
9,55.0,b'Private',104996.0,b'7th-8th',4.0,b'Married-civ-spouse',b'Craft-repair',b'Husband',b'White',b'Male',0.0,0.0,10.0,b'United-States',b'<=50K'

In [3]:
census_types = adult_census.dtypes
census_types

age               float64
workclass          object
fnlwgt            float64
education          object
education-num     float64
marital-status     object
occupation         object
relationship       object
race               object
sex                object
capital-gain      float64
capital-loss      float64
hours-per-week    float64
native-country     object
class              object
dtype: object

In [4]:
target_name = "class"
target = adult_census[target_name].astype("category").str.decode('utf-8')
target

0        <=50K
1        <=50K
2         >50K
3         >50K
4        <=50K
         ...
48837    <=50K
48838     >50K
48839    <=50K
48840    <=50K
48841     >50K
Name: class, Length: 48842, dtype: object

In [5]:
features_num = census_types[census_types != 'object']
features_num_names = sorted(features_num.index)
features_num_names.remove('fnlwgt')
features_num_Df = adult_census[features_num_names]
features_num_Df.columns

Index(['age', 'capital-gain', 'capital-loss', 'education-num',
       'hours-per-week'],
      dtype='object')

In [6]:
features_num_Df

        age  capital-gain  capital-loss  education-num  hours-per-week
0      25.0           0.0           0.0            7.0            40.0
1      38.0           0.0           0.0            9.0            50.0
2      28.0           0.0           0.0           12.0            40.0
3      44.0        7688.0           0.0           10.0            40.0
4      18.0           0.0           0.0           10.0            30.0
...     ...           ...           ...            ...             ...
48837  27.0           0.0           0.0           12.0            38.0
48838  40.0           0.0           0.0            9.0            40.0
48839  58.0           0.0           0.0            9.0            40.0
48840  22.0           0.0           0.0            9.0            20.0
48841  52.0       15024.0           0.0            9.0            40.0

[48842 rows x 5 columns]

In [7]:
model = KNN()
_ = model.fit(features_num_Df, target)

In [8]:
target_predicted = model.predict(features_num_Df)
(target_predicted == target).mean()

np.float64(0.8479791982310306)

The score method is the same as comparing actual class with predicted class. I do not see a big difference with KNN between using test or training data in the score method.

In [9]:
model.score(features_num_Df, target)

0.8479791982310306